### ISSUE TITLE
Website crashes when clicking the purchase button

### ISSUE THREAD

**Issue by Teirpo** [manuel-rw/grocy-scanner#15]
Newbie here
Maybe I configured something wrong, but as soon as I klick the purchase button the website crashes and I have to reload it.
I have created Locations and quantities.
![2024-08-31_15h25_09](https://github.com/user-attachments/assets/7f7dbb69-82f9-4f9e-898f-5994d5ef4ea3)

[_grocy-scanner_logs(1).txt](https://github.com/user-attachments/files/16824840/_grocy-scanner_logs.1.txt)
```
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://192.168.1.130:9283//api/objects/product_barcodes?query%5B%5D=barcode%3D8801043032308
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://192.168.1.130:9283//api/objects/product_barcodes?query%5B%5D=barcode%3D8801043032308
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 142.8659ms - 404
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 173.4854ms - 404
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET https://www.coop.ch/de/dynamic-pageload/searchresultJson?componentName=searchresultJson&url=%2Fde%2Fsearch%2F%3Ftext%3D8801043032308&displayUrl=%2Fde%2Fsearch%2F%3Ftext%3D8801043032308&compiledTemplates%5B%5D=productTile-new&compiledTemplates%5B%5D=sellingBanner&_=1725109370322
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://www.coop.ch/de/dynamic-pageload/searchresultJson?componentName=searchresultJson&url=%2Fde%2Fsearch%2F%3Ftext%3D8801043032308&displayUrl=%2Fde%2Fsearch%2F%3Ftext%3D8801043032308&compiledTemplates%5B%5D=productTile-new&compiledTemplates%5B%5D=sellingBanner&_=1725109370322
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET https://www.migros.ch/authentication/public/v1/api/guest?authorizationNotRequired=true
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://www.migros.ch/authentication/public/v1/api/guest?authorizationNotRequired=true
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 537.6736ms - 403
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 537.9388ms - 403
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 603.8298ms - 200
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 604.1042ms - 200
fail: GrocyScanner.Core.Providers.CoopProductProvider[0]
      Failed to fetch coop product: 8801043032308 - <html><head><title>coop.ch</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAigfXuVU2CSgAssX4Gw==','hsh':'4E2D21855D176C1885A97CE16C8EC3','t':'fe','s':49043,'e':'da4839820938a38271195fec9619e828d317ca7e112c2afb70e4415ec0d34152','host':'geo.captcha-delivery.com'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at GrocyScanner.Core.Providers.CoopProductProvider.GetProductByGtin(String gtin) in /src/GrocyScanner.Core/Providers/CoopProductProvider.cs:line 37
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request POST https://www.migros.ch/onesearch-oc-seaapi/public/v5/search
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request POST https://www.migros.ch/onesearch-oc-seaapi/public/v5/search
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 73.2185ms - 200
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 73.4049ms - 200
fail: GrocyScanner.Core.Providers.MigrosProductProvider[0]
      Unexpected count for gtin 8801043032308: 0
info: GrocyScanner.Core.GrocyClient.GrocyClient[0]
      Obtaining locations and quantity units
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://192.168.1.130:9283//api/objects/locations
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://192.168.1.130:9283//api/objects/locations
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 140.103ms - 404
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 140.4629ms - 404
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
      System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
       ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
         at GrocyScanner.Core.GrocyClient.GrocyLocationMasterData.GetLocationsAsync() in /src/GrocyScanner.Core/GrocyClient/GrocyLocationMasterData.cs:line 29
         at GrocyScanner.Core.GrocyClient.GrocyClient.UpsertProduct(Product product, Int32 amount, Nullable`1 bestBefore, Nullable`1 price) in /src/GrocyScanner.Core/GrocyClient/GrocyClient.cs:line 88
         at GrocyScanner.Service.Shared.Components.AddProductDialog.OnClickPurchase() in /src/GrocyScanner.Service/Shared/Components/AddProductDialog.razor:line 156
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'w3QGB17ny5nq1a51KA0z0ZTZgUjV5PNrSGBUqIArOF4'.
      System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
       ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
         at GrocyScanner.Core.GrocyClient.GrocyLocationMasterData.GetLocationsAsync() in /src/GrocyScanner.Core/GrocyClient/GrocyLocationMasterData.cs:line 29
         at GrocyScanner.Core.GrocyClient.GrocyClient.UpsertProduct(Product product, Int32 amount, Nullable`1 bestBefore, Nullable`1 price) in /src/GrocyScanner.Core/GrocyClient/GrocyClient.cs:line 88
         at GrocyScanner.Service.Shared.Components.AddProductDialog.OnClickPurchase() in /src/GrocyScanner.Service/Shared/Components/AddProductDialog.razor:line 156
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
``` 

Has anyone else had this problem or knows a fix for it?

**Comment by manuel-rw** [comment]
Hi, thanks for the post. I will look into this.
